import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
// import AuthProvider from "../components/sessionprovider";
// import { Provider } from "react-redux";
// import { store } from "@/store/store";
import Providers from './providers/providers'

const roboto = Roboto({
  subsets: ['latin'], // Specify the subset to load (e.g., latin)
  weight: ['400', '500', '700'], // Define the weights you want
  display: 'swap', // Ensures text is visible while font is loading
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
